def ClumpFinding(Genome, k, L,t):
    x = 0
    clump = set()
    while (x+L)<=len(Genome):
        substrate = {}
        y = Genome[x:x+L]
        z = 0
        while (z+k)<=len(y):
            sub = y[z:z+k]
            if sub not in substrate:
                substrate[sub] = 1
            else :
                substrate[sub]+=1
            z+=1
        x+=1
        clumpList = [key for key in substrate.keys() if substrate[key]>=t]
        for l in clumpList:
            clump.add(l)
    return len(clump)

Genome = "GGAGAAGAGAAGTCAAAGTCAAAGTCACACCTTCCTTTTTCCTACACTAAAACCTACACTCTACACTAATCCCAATTTGGCTTCGCTCCCCAAGATACGACGTCAGCCCTAGCACCATCGCCTGTTATGTGTATCTTGCCGTGGGGTATTACATACATACTTATACTTCGCGATACTTCGCATAGACCTTGTCGTACTGGGAATCCACCGAGGCGATTAATACTTAAAAAGGCCGGTTTGTAGACTGATACTCGTGTTCCGCTGGACCGCTGCTGGACCCCTGGACCCTGACATGAACGCCATGATAACCTTAACCTCTGGTACGGATTCTACTCGGAGCAATGATACTCTCAAAAACTCCGACTCCGACTACTCCGCTAATGTCTGACGCACCGGTTAACAATACATCTAATGGCGAGCAACGTTACCAAAACGAGAACCTAATCAGAACTTTCGGACTTTAAACTGGAGTTCACGTCCGGTGTACGATTGCCAGCATTTGTAGAGCGTGGCAGAATTGCTCTACTATATCGTGCACTCTATATCGTGTATATGAGAATGAGATGTGATGTATGTGAATGGTCTCCCGTGCCGTGAGCTCCGTGAGGGGAACGGGAACGGTAACGGTATTTTCTGTACGATGGTTTATGGGAATCATTAGGGACATTAGGGAATTCATTAGGGATGCGTAGGCGCCCCGTAGGCAGACCTCTTTGCCGGAAGCGTAACCGTGTCATCGAGCAACGGATTAGACAAGTCTGTGACTACTGCTTTAGTGACGAGCTCCCGTGGCAAAAGGATATTGACGCGTCGCTGTTGGCCGTTAATGCCGTGCCGTGCCGTTAATTCCAGGCGGCTATCATACTTTCCACATGCTTAAATAGCAGGCGTCGGTATAGAGCGGTGTCCTGGAGAAGATATCCCTTTGTCCACCGTAGTAGGTAGTTAGCCCCGATATATCGATATCGACTTTTATCGACTTTTTACACGATGGTACGGAGGGTGCCAGTCCAGCGTAGGTGCAATTCTCCTGCCTAACCATCACATCTTTAGGACAAGACTAAGGTTGTGGTCCGAGCGCAGTGGTACCAGGTTACCAAGTGATTCCTACGAGACCGGATGGGGGTGGGCCGGTGCGACGGAAAGTGACTGGTTCATATTGGGGACCACGATCGACCCACGCTTGACTTGTCTCCTGATTCATCAAGTGGTGTGGTGTTTCAAGTGGTAGAGAAGGGGCATCTGTTTCACAGTGGTCCCTGGAGCATAGAGTCACTAGTGGTGAGCAGCGCATCGCGGGGCGTAGTCGATCGTTCCCAGACATATTTTAATTAGTTACTCTAGGTGGGGATCAATCGAGCGCTCCTATCGCGGTCAGAATCGACGAGACCTCTGTGTACAGTATTCGATGGTGGGTGGGGTGGTGGGGTGGCGGGGTGCGAGGCTTCACTCCAGCAGATGGTCAGGGAACTGCGCATGGTACGCCTACGCGGGGCCTCAACACTGCTGCTACACACTGCTGACTGCTGTTGTGTACTATCGATCATGGCCGATTGCTTAATGCCAAAACATGCTTGCTCGGCCATCAGCTGTACTACTATGTCTTTTCTGCTTCGGTATCAACACTCGTCCTGTCCCTTAGTGATGAGATGGTAGCACCGGAAAGATCTCATCGTAGATGGTGTCGCACGGGTAGTCCTATTAATCGATTGGTATTGGACAACCGGGCTTTGGGGGAGCGAGGGGGGGGGGGGGGGTCTACACGCGTTATAGTCTAGAATCTTATAATTCCGCGACACTAGTTGTAGATCATGAAGGTGGATTGACTGCTTACTCAGAACTCCCCCGCCAGCTGCCCAGAAGTGCCTGACTGCACTGGCACACTTCGGGGACAGTGCGATGTATAGAACAAGCCTGACGTAGAGTGACCGTTACATTTCGTTGAGTGC"
k = 9
L = 25
t = 4
print (ClumpFinding(Genome, k, L,t))