def FrequentWords(Text, k):
    words = []
    freq = FrequencyMap(Text, k)
    m = max(freq.values())
    for key in freq:
        if freq[key] == m:
            words.append(key)
    return words

def FrequencyMap(Text, k):
    freq = {}
    n = len(Text)
    for i in range(n - k + 1):
        Pattern = Text[i:i + k]
        freq[Pattern] = 0
    for key in freq:
        freq[key] = PatternCount(Text, key)
    return freq

def PatternCount(Text, Pattern):
    count = 0
    for i in range(len(Text)-len(Pattern)+1):
        if Text[i:i+len(Pattern)] == Pattern:
            count = count+1
    return count 
print(FrequentWords('AGAAGGAAAGAAGGAATACCCAGCTCGTAGCTTACCCAGCTACCCATAATTACCCATAATTACCCAGCAGAAGGAATCGTAGCTTCGTAGCTTACCCAGCTACCCAGCTACCCATAATAGAAGGAATACCCAGCTACCCATAATTCGTAGCTAGAAGCTTAAGAAGGAATACCCATAATTACCCATAATAGAAGCTTATACCCATAATAGAAGGAATCGTAGCTAGAAGGAAAGAAGCTTATCGTAGCTTCGTAGCTAGAAGGAAAGAAGCTTAAGAAGGAATCGTAGCTTACCCAGCTACCCATAATTACCCATAATAGAAGGAATACCCATAATTACCCAGCAGAAGGAATACCCAGCTACCCAGCTACCCAGCTACCCATAATTACCCAGCTACCCATAATAGAAGCTTATACCCATAATTACCCAGCTCGTAGCTTACCCATAATTACCCATAATAGAAGGAATCGTAGCTAGAAGGAATACCCAGCTACCCAGCAGAAGGAATACCCAGCAGAAGCTTATCGTAGCTTACCCAGCTACCCAGCTACCCAGCAGAAGCTTATCGTAGCTAGAAGCTTAAGAAGCTTATACCCATAATAGAAGCTTAAGAAGCTTATACCCATAATTACCCATAATTCGTAGCTTACCCATAATTACCCATAATAGAAGCTTAAGAAGGAATACCCATAATAGAAGCTTAAGAAGCTTATCGTAGCTTACCCAGCAGAAGGAATACCCATAATTACCCATAATTACCCATAATTACCCATAATTACCCAGCTACCCATAATTCGTAGCTTCGTAGCTAGAAGCTTAAGAAGGAATACCCATAATAGAAGGAATCGTAGCTTACCCATAATAGAAGCTTATCGTAGCTAGAAGGAAAGAAGGAAAGAAGCTTATACCCATAAT',11))